In [ ]:
# There are some built-in or importable or installable modules in Python, which can be used to perform various types 
# of functions

In [ ]:
# These are some popular packages:

# NumPy - Numerical Python (NumPy) - Data Management & Fundamental Statistics, etc
# Pandas - Panel Data (Pandas) - Data Management, Exploration, Visualization, Processing, etc
# Matplotlib - Visualization/Plotting Graphs/etc
# Plotly - Visualization/Plotting Graphs
# Seaborn - Visualization/Plotting Graphs
# Scikit (Sklearn) - Machine Learning 
# statsmodels - core statistics/hypothesis testing/linear models

In [ ]:
# What is a package?

# A package in Python is  collection of functions/methods, which can be used to perform certain operations.

# Assume you need to average value of some array

In [3]:
aList = [1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
# To calculate average, the formula is

# Sum of all values / Count of values

In [5]:
sum(aList) / len(aList)

4.5

In [ ]:
# How to import a package in Python?

In [1]:
import numpy

In [ ]:
# Numpy Sequence / Data Structure

# Numpy Array is just another data structure jut like List, Tuple

In [6]:
numpy.array(aList).mean()

4.5

In [7]:
numpy_arr = numpy.array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
type(aList)

list

In [9]:
type(numpy_arr)

numpy.ndarray

In [10]:
num_aList = numpy.array(aList)

In [11]:
aList

[1, 2, 3, 4, 5, 6, 7, 8]

In [12]:
num_aList

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
num_aList.mean()

4.5

In [ ]:
# Why numpy has its own datatype?

# Why don't it use the list straight away?

In [21]:
bList = [1, 2, 3, 4, 5, 1, 2, 3, 4, 5,1, 2, 3, 4, 5,1, 2, 3, 4, 5,1, 2, 3, 4, 5,1, 2, 3, 4, 5,1, 2, 3, 4, 5,1, 2, 3, 4, 5,1, 2, 3, 4, 5,1, 2, 3, 4, 5,1, 2, 3, 4, 5,1, 2, 3, 4, 5,1, 2, 3, 4, 5, '5', 'a', 1, 2, 3, 4, 5,1, 2, 3, 4, 5,1, 2, 3, 4, 5,1, 2, 3, 4, 5]

In [29]:
type(bList[0])

int

In [30]:
for b in bList:
    print (type(b))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'str'>
<class 'str'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class

In [22]:
sum(bList) / len(bList)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [24]:
num_bList = numpy.array(bList)

In [25]:
num_bList

array(['1', '2', '3', '4', '5', '1', '2', '3', '4', '5', '1', '2', '3',
       '4', '5', '1', '2', '3', '4', '5', '1', '2', '3', '4', '5', '1',
       '2', '3', '4', '5', '1', '2', '3', '4', '5', '1', '2', '3', '4',
       '5', '1', '2', '3', '4', '5', '1', '2', '3', '4', '5', '1', '2',
       '3', '4', '5', '1', '2', '3', '4', '5', '1', '2', '3', '4', '5',
       '5', 'a', '1', '2', '3', '4', '5', '1', '2', '3', '4', '5', '1',
       '2', '3', '4', '5', '1', '2', '3', '4', '5'], dtype='<U11')

In [26]:
num_bList.dtype

dtype('<U11')

In [31]:
# NumPy

In [ ]:
# to create a numpy array
# numpy.array()

In [35]:
a1 = numpy.array([1, 2, 3, 4, 5, 6])
b1 = numpy.array([10, 20, 30, 40, 50, 60])

In [34]:
a1 + b1

array([11, 22, 33, 44, 55, 66])

In [36]:
c1 = numpy.array( (1, 2, 3, 4, 5, 6) )

In [37]:
c1

array([1, 2, 3, 4, 5, 6])

In [38]:
c1 = numpy.array( [1, 2, 3, 4, 5, 6] ) # 1 positional arguments

ValueError: only 2 non-keyword arguments accepted

In [ ]:
# Python functions

In [ ]:
# What is a function in Python / Programming?

# A function is set of commands to perform some operation

In [ ]:
# A function to add two values

In [39]:
a = 1
b = 2

c = a**2 + b**2
d = c*x / y

In [40]:
a = 1
b = 2

In [ ]:
# How to define a function

# def <Function Name without space> ():
#<indent> function statement    

In [41]:
# Function definition
def add(a, b):
    print (a + b)

In [ ]:
# There two things associated with functions

# First you define them

# Then you call them

In [43]:
# Function call
add(5, 10)

15


In [44]:
add(20, 30)

50


In [46]:
# Function definition
def add(a, b):
    print (a + b)

# Function call
add(10, 20)

30


In [47]:
add(a, b)

3


In [ ]:
# Scope of variable

# Scope of variable describes the area of use.
# For example, a variable inside function cannot be used outside of the function

# A variable defined outside of function can be used in the function

In [50]:
def valueofX():
    x = 10
    print (x)

In [49]:
x

NameError: name 'x' is not defined

In [51]:
valueofX()

10


In [52]:
x

NameError: name 'x' is not defined

In [53]:
def valueofX2():
    print (x)

In [54]:
x = 20
valueofX2()

20


In [55]:
def valueofY():
    print (y)

In [56]:
y = 30
valueofY()

30


In [57]:
del y

In [58]:
valueofY()

NameError: name 'y' is not defined

In [59]:
valueofZ()

def valueofZ():
    print (z)

NameError: name 'valueofZ' is not defined

In [60]:
def valueofZ():
    print (z)

In [61]:
valueofZ()

NameError: name 'z' is not defined

In [62]:
z = 20
valueofZ()

20


In [64]:
def valueofZ():
    print (z)

    
z = 20    
valueofZ()

20


In [65]:
def add_values(x, y): #(x,y) are called positional arguments
    print (x+y)

In [66]:
add_values(50, 30)

80


In [67]:
add_values()

TypeError: add_values() missing 2 required positional arguments: 'x' and 'y'

In [68]:
add_values(50, 30, 49, 59)

TypeError: add_values() takes 2 positional arguments but 4 were given

In [69]:
def myfun(list1):
    print (sum(list1))

In [94]:
a = [1, 2, 3, 4, 5, 6]

In [95]:
myfun(a)

21


In [96]:
def sum_of_list(list1):
    print (sum(list1))

In [97]:
sum_of_list(a)

21
